import tkinter as tk
from tkinter import ttk
root=tk.Tk()
root.title("User Info")
name=ttk.Label(root,text="Enter Your Name:")
name_var=tk.StringVar()
name_entry=ttk.Entry(root,width=16,textvariable=name_var)
name.grid(row=0,column=0,sticky=tk.W)
name_entry.grid(row=0,column=1)
age=ttk.Label(root,text="Enter Your Age:")
age_var=tk.StringVar()
age_entry=ttk.Entry(root,width=16,textvariable=age_var)
age.grid(row=1,column=0,sticky=tk.W)
age_entry.grid(row=1,column=1)
email=ttk.Label(root,text="Email:")
email_var=tk.StringVar()
email_entry=ttk.Entry(root,width=16,textvariable=email_var)
email_entry.grid(row=2,column=1)
email.grid(row=2,column=0,sticky=tk.W)
root.mainloop()
